### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/coder-html-css-lessons#4]
- [ ] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [ ] extras.yml
- [x] overview.md
- [x] learn.md
- [x] lesson.md
- [x] ks.md

**Comment by lauraclay** [comment]
coder.png and login.png need moved to lesson folders, and capitalisation removed on these folders.

**Comment by MissPhilbin** [comment]
A component image required for hardware.yml of a computer attached to network (@bennuttall can you check what I've done is correct for hardware and software?)

**Comment by bennuttall** [comment]
This resource requires some amendments to the template to allow for non-Raspbian use of a Pi, and maybe some other changes as it's quite different.
